# Generated by Django 3.1.7 on 2021-03-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='petdate',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='vet.office'),
        ),
    ]
